swagger: '2.0'
info:
  description: 'Documentation of the Central Server API by AutoTF'
  version: 1.0.0
  title: Central Server API
  contact:
    email: contact@autotf.de
host: "<evuName>.server.autotf.de"
tags:
  - name: Tokens
    description: Endpoints to get the authentik tokens
  - name: Mac Address
    description: Endpoints to get and add mac addresses to the database.
schemes:
  - https
paths:
  /token:
    get:
      tags:
        - Tokens
      summary: Returns the token HTML page
      description: Serves a static HTML page used for token handling.
      produces:
        - text/html
      responses:
        '200':
          description: HTML page returned successfully
          schema:
            type: string
            example: "<html><body>...</body></html>"
  /tokenStep:
    get:
      tags:
        - Tokens
      summary: Redirects to token endpoint with query and cookie-based tokens
      description: |
        Reads the `csrf_token` from the query string and a proxy token from cookies.
        If both are present, redirects to `localhost:5000/token` with those values as query parameters.
        Otherwise, returns a plain text response.
      parameters:
        - name: csrf_token
          in: query
          required: true
          type: string
          description: CSRF token from the query string
      produces:
        - text/plain
      responses:
        302:
          description: Redirects to `localhost:5000/token` with query parameters
        200:
          description: Tokens not found (plain text response)
          schema:
            type: string
            example: Tokens not found.
            
            
            
  /lastmacaddrsupdate:
    get:
      tags:
        - Mac Address
      summary: Get the timestamp of the last MAC address update
      description: Returns the last updated timestamp in `dd.MM.yyyy HH:mm:ss` format.
      produces:
        - text/plain
      responses:
        200:
          description: Last update timestamp
          schema:
            type: string
            example: "16.04.2025 14:32:10"
  /macAddress:
    get:
      tags:
        - Mac Address
      summary: Get all MAC addresses
      description: Returns a list of all known MAC addresses.
      produces:
        - application/json
      responses:
        200:
          description: List of MAC addresses
          schema:
            type: array
            items:
              type: string
              example: "00:1A:2B:3C:4D:5E"
  /addAddress:
    post:
      tags:
        - Mac Address
      summary: Add a new MAC address
      description: Adds a new MAC address to the system.
      consumes:
        - application/json
      parameters:
        - name: address
          in: body
          required: true
          schema:
            type: string
            example: "00:1A:2B:3C:4D:5E"
      responses:
        200:
          description: MAC address added successfully
        400:
          description: Error adding MAC address
          schema:
            type: string
            example: "An error occurred while adding the mac address."
externalDocs:
  description: Find out more about AutoTF
  url: https://autotf.de
